### PR TITLE
Widespread CD*, DR* inductors plus the whole Murata product line footprints

### PR DESCRIPTION
**Pull request by anpaza**
This pull request may look a little too large, but it's worth it.

The CD\* series of unshielded SMD inductors is relatively widespread. This patch adds footprints for most common sizes - CD32, 43, 54, 73, 75, 104, 105 using pad sizes from manufacturer datasheets.

The DR\* series of shielded SMD inductors is also widely known, most notably the DR127 size.

Also I took Murata's product catalogue and entered footprint data into a table which I used to generate footprints with the murata_gen.py script which can be found here:
https://github.com/anpaza/kicad-libs/tree/master/Choke_SMD

All footprints were checked with check_kicad_mod.py script and they pass all tests with the following exceptions:
- Some footprints have several variants for wave, reflow and hand soldering. Footprint name has the _Wave, _Reflow etc suffixes but obviously they use same 3D model (which has no suffix at all). Thus, check_kicad_mod complains about rule 10.7.
- Some footprints are detected as violating rule 6.5 because for very small footprints (like 0402 and even smaller) I was forced to use 0.1mm lines on silkscreen, otherwise the whole footprint sinks under the very big (relative) silkscreen lines. I think KLC should be a bit more permissive here, like the rule about courtyard for small parts.

All footprints have 3D models, made by hand in Blender. I will add a pull request for the kicad-library repository as well.

The link above contains the Choke_SMD.kicad_pcb file (autogenerated) which contains all the inductors at once. It would be easier to review them all in a single file. The 3D shapes will display properly if you copy the wrl files to /usr/.../Choke_SMD.3dshapes/

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @anpaza I like that you are scripting these. I will have a look over these when I have time, for now I'll point you in the direction of the great scripting tool being developed by @pointhi https://github.com/pointhi/kicad-footprint-generator 

Have a look at the ./scripts directory, I think that will be of great assistance if you ever want to generate further components.

**Comment by anpaza** [comment]
Thank you for pointing to that script, I'll certainly try to use it next time I'll need to generate footprints.
Also would be cool to have a Blender plugin (which are written, surprise, also in Python) to generate 3D models :)

**Comment by SchrodingersGat** [comment]
@anpaza see here https://github.com/KiCad/kicad-library/issues/257 we'll deal with this once the repositories are sorted out. I like what you have done, though.

**Comment by SchrodingersGat** [comment]
Also if you're interested in generating 3D models with python... https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator

**Comment by anpaza** [comment]
Any news?

**Comment by SchrodingersGat** [comment]
@ashtonchase  @diggit  @CarlPoirier we need to work out how we proceed with the various Choke* and Inductor* repositories. This is a really good PR and there are also a lot that are outstanding in https://github.com/KiCad/Inductors.pretty/pulls

Does anyone have any strong opinions? I have previously raised this here (https://github.com/KiCad/kicad-library/issues/257) without response.

Sorry to keep you waiting @anpaza we're trying to consolidate the library structure :)

**Comment by SchrodingersGat** [comment]
@CarlPoirier when you have adjusted the Chokes / Inductors libraries please leave a comment here so that @anpaza  can have his contributions merged in :)

**Comment by SchrodingersGat** [comment]
(see https://github.com/KiCad/kicad-library/issues/257#issuecomment-252781042)

**Comment by anpaza** [comment]
Oh my! He moves! He's alive!
:)

**Comment by jkriege2** [comment]
Hi!

this repo has been deprecatd. Please resubmit you PR to the new SMD/THT-inductors repo, using the naming standard used there:
https://github.com/KiCad/Inductors_SMD.pretty
https://github.com/KiCad/Inductors_THT.pretty

Best,
 JAN

**Comment by SchrodingersGat** [comment]
@anpaza please submit this PR as @jkriege2 has said above - we do not want to waste your good work!

**Comment by evanshultz** [comment]
@anpaza Will you be able to re-submit this PR to the new library mentioned above soon?

**Comment by anpaza** [comment]
Will try to do it on these holidays.

**Comment by SchrodingersGat** [comment]
Hi @anpaza sorry for the delay in chasing this up - was there ever a resolution to this? Have these footprints been resubmitted to the new repos?

**Comment by SchrodingersGat** [comment]
@anpaza sorry that this never got addressed. We have slowly been working through all the outstanding issues (almost there!)

This repository is now marked as deprecated, can you please resubmit these footprints to https://github.com/kiacd/kicad-footprints

Thanks very much :)

**Pull request closed without merging**
