### PR TITLE
Move to Choke_SMD.pretty, move text, add fab

### PR DESCRIPTION
**Pull request by evanshultz**
This is a continuation of the work from https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/30#issuecomment-269087547.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

looks good to me, there's only one KLC-breach, created when renaming the file: You also have to rename the footprint within the file! 

```
checking module: Transformer_current_SMD_8.4x7.2mm
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
```

Please fix, then I think I can merge :-)

best,
JAN

**Comment by evanshultz** [comment]
Oh wow. My mistake. Please go for it!

**Comment by evanshultz** [comment]
Oops! Wrong button.

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
